package com.attendance.entity;
// Generated Sep 29, 2016 12:40:42 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendancedetails generated by hbm2java
 */
@Entity
@Table(name = "attendancedetails", catalog = "attendancemanagement")
public class AttendanceDetails implements java.io.Serializable {

	private Integer attendanceId;
	private Employee employee;
	private Date swipeIn;
	private Date swipeOut;
	private Date lastUpdated;


	private Integer totalHours;
	private String machineName;

	public AttendanceDetails() {
	}

	public AttendanceDetails(Employee employee, String machineName) {
		this.employee = employee;
		this.machineName = machineName;
	}

	public AttendanceDetails(Employee employee, Date swipeIn, Date swipeOut, Integer totalHours, String machineName) {
		this.employee = employee;
		this.swipeIn = swipeIn;
		this.swipeOut = swipeOut;
		this.totalHours = totalHours;
		this.machineName = machineName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "attendance_id", unique = true, nullable = false)
	public Integer getAttendanceId() {
		return this.attendanceId;
	}

	public void setAttendanceId(Integer attendanceId) {
		this.attendanceId = attendanceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "employeeid", referencedColumnName = "employeeid", nullable = false),
			@JoinColumn(name = "access_cardno", referencedColumnName = "access_cardno", nullable = false) })
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "swipe_in", length = 19)
	public Date getSwipeIn() {
		return this.swipeIn;
	}

	public void setSwipeIn(Date swipeIn) {
		this.swipeIn = swipeIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "swipe_out", length = 19)
	public Date getSwipeOut() {
		return this.swipeOut;
	}

	public void setSwipeOut(Date swipeOut) {
		this.swipeOut = swipeOut;
	}

	@Column(name = "total_hours")
	public Integer getTotalHours() {
		return this.totalHours;
	}

	public void setTotalHours(Integer totalHours) {
		this.totalHours = totalHours;
	}

	@Column(name = "machineName", nullable = false, length = 60)
	public String getMachineName() {
		return this.machineName;
	}

	public void setMachineName(String machineName) {
		this.machineName = machineName;
	}
	
	/**
	 * @return the lastUpdated
	 */
	public Date getLastUpdated() {
		return lastUpdated;
	}

	/**
	 * @param lastUpdated the lastUpdated to set
	 */
	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
