package com.attendance.entity;
// Generated Sep 29, 2016 12:40:42 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locationdetails generated by hbm2java
 */
@Entity
@Table(name = "locationdetails")
public class LocationDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -92002055339552981L;
	private int locationId;
	private String locationName;
	private String machineName;

	private String block;
	private String floor;
	private String wing;
	private Set<MachineDetails> machinedetailses = new HashSet<MachineDetails>();
	private Set<Employee> employees = new HashSet<Employee>();

	public LocationDetails() {
	}

	public LocationDetails(int locationId, String locationName, String block, String floor, String wing) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.block = block;
		this.floor = floor;
		this.wing = wing;
	}

	public LocationDetails(int locationId, String locationName, String block, String floor, String wing,
			Set machinedetailses, Set employees) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.block = block;
		this.floor = floor;
		this.wing = wing;
		this.machinedetailses = machinedetailses;
		this.employees = employees;
	}

	@Id

	@Column(name = "locationId", unique = true, nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	@Column(name = "locationName", nullable = false, length = 20)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "Block", nullable = false, length = 20)
	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	@Column(name = "Floor", nullable = false, length = 20)
	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	@Column(name = "Wing", nullable = false, length = 20)
	public String getWing() {
		return this.wing;
	}

	public void setWing(String wing) {
		this.wing = wing;
	}

	/**
	 * @return the machineName
	 */
	public String getMachineName() {
		return machineName;
	}

	/**
	 * @param machineName
	 *            the machineName to set
	 */
	public void setMachineName(String machineName) {
		this.machineName = machineName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationdetails")
	public Set<MachineDetails> getMachinedetailses() {
		return this.machinedetailses;
	}

	public void setMachinedetailses(Set<MachineDetails> machinedetailses) {
		this.machinedetailses = machinedetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationdetails")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
