package com.attendance.entity;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locationdetails generated by hbm2java
 */
@Entity
@Table(name = "locationdetails", catalog = "test")
public class LocationDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id

	@Column(name = "locationId", unique = true, nullable = false)
	private long locationId;
	private String locationName;
	private String block;
	private String floor;
	private String wing;
	@OneToMany(cascade = CascadeType.PERSIST)
	@JoinColumn(name = "locationId")
	private List<Employee> employees;
	@ElementCollection(targetClass = Employee.class)
	private Set<MachineDetails> machinedetailses = new HashSet<MachineDetails>();

	public LocationDetails() {
	}

	public LocationDetails(long locationId, String locationName, String block, String floor, String wing) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.block = block;
		this.floor = floor;
		this.wing = wing;
	}

	public LocationDetails(long locationId, String locationName, String block, String floor, String wing,
			List<Employee> employees, Set<MachineDetails> machinedetailses) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.block = block;
		this.floor = floor;
		this.wing = wing;
		this.employees = employees;
		this.machinedetailses = machinedetailses;
	}

	public long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(long locationId) {
		this.locationId = locationId;
	}

	@Column(name = "locationName", nullable = false, length = 20)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "Block", nullable = false, length = 10)
	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	@Column(name = "Floor", nullable = false, length = 2)
	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	@Column(name = "Wing", nullable = false, length = 5)
	public String getWing() {
		return this.wing;
	}

	public void setWing(String wing) {
		this.wing = wing;
	}

	public List<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationdetails")
	public Set<MachineDetails> getMachinedetailses() {
		return this.machinedetailses;
	}

	public void setMachinedetailses(Set<MachineDetails> machinedetailses) {
		this.machinedetailses = machinedetailses;
	}

}
