package com.attendance.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Machinedetails generated by hbm2java
 */
@Entity
@Table(name = "machinedetails", catalog = "test")
public class MachineDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String machineId;
	private Employee employee;
	private LocationDetails locationdetails;
	private String activationStatus;
	private Set<AttendanceDetails> attendancedetailses = new HashSet<AttendanceDetails>();

	public MachineDetails() {
		/**
		 * 
		 */
	}

	/**
	 * 
	 * @param machineId
	 * @param location
	 * @param machineType
	 */

	public MachineDetails(String machineId, String location, String machineType) {
		this.machineId = machineId;
		this.employee = employee;
	}

	/**
	 * 
	 * @param machineId
	 * @param location
	 * @param machineType
	 * @param attendancedetailses
	 * @param employees
	 */
	public MachineDetails(String machineId, String location, String machineType,
			Set<AttendanceDetails> attendancedetailses, Set<Employee> employees) {
		this.machineId = machineId;
		this.employee = employee;
		this.locationdetails = locationdetails;
		this.activationStatus = activationStatus;
		this.attendancedetailses = attendancedetailses;
	}

	@Id
	@Column(name = "machine_id", unique = true, nullable = false, length = 20)
	public String getMachineId() {
		return this.machineId;
	}

	public void setMachineId(String machineId) {
		this.machineId = machineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "employeeid", referencedColumnName = "employeeid", nullable = false),
			@JoinColumn(name = "access_cardno", referencedColumnName = "access_cardno", nullable = false) })
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "locationId")
	public LocationDetails getLocationdetails() {
		return this.locationdetails;
	}

	public void setLocationdetails(LocationDetails locationdetails) {
		this.locationdetails = locationdetails;
	}

	@Column(name = "activation_status", length = 5)
	public String getActivationStatus() {
		return this.activationStatus;
	}

	public void setActivationStatus(String activationStatus) {
		this.activationStatus = activationStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "machinedetails")
	public Set<AttendanceDetails> getAttendancedetailses() {
		return this.attendancedetailses;
	}

	public void setAttendancedetailses(Set<AttendanceDetails> attendancedetailses) {
		this.attendancedetailses = attendancedetailses;
	}

}
