package com.attendance.entity;
// Generated Sep 28, 2016 7:33:38 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Machinedetails generated by hbm2java
 */
@Entity
@Table(name = "machinedetails", catalog = "attendancemanagement")
public class MachineDetails implements java.io.Serializable {

	private Integer machineId;
	private Employee employee;
	private LocationDetails locationdetails;
	private String activationStatus;

	public MachineDetails() {
	}

	public MachineDetails(Employee employee, LocationDetails locationdetails, String activationStatus) {
		this.employee = employee;
		this.locationdetails = locationdetails;
		this.activationStatus = activationStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "machineId", unique = true, nullable = false)
	public Integer getMachineId() {
		return this.machineId;
	}

	public void setMachineId(Integer machineId) {
		this.machineId = machineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "employeeid", referencedColumnName = "employeeid", nullable = false),
			@JoinColumn(name = "access_cardno", referencedColumnName = "access_cardno", nullable = false) })
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "machineName", nullable = false)
	public LocationDetails getLocationdetails() {
		return this.locationdetails;
	}

	public void setLocationdetails(LocationDetails locationdetails) {
		this.locationdetails = locationdetails;
	}

	@Column(name = "activation_status", nullable = false, length = 20)
	public String getActivationStatus() {
		return this.activationStatus;
	}

	public void setActivationStatus(String activationStatus) {
		this.activationStatus = activationStatus;
	}

}
